KhuyenNghiDauTu/PhimHang.vn/Controllers/RecommendationController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PhimHang.Models;
using System.IO;

namespace PhimHang.Controllers
{
    [Authorize]
    public class RecommendationController : Controller
    {
        private KNDTLocalConnection db = new KNDTLocalConnection();
        private StoxDataEntities dbstox = new StoxDataEntities();
        // GET: /Recommendation/
        public ActionResult BuyRecommend()
        {
            //ViewBag.PostBy = new SelectList(db.UserLogins, "Id", "KeyLogin");
            LoadInit();

            return View();
        }
        private const string ImageURLAvata = "/Chart/";
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> BuyRecommend([Bind(Include = "ID,StockCode,BuyPrice,StockHoldingTime,TargetSell,Description,CreatedDate,PostBy,ChartImange")] BuyRecommendModel buyRecommendModel)
        {
            if (ModelState.IsValid)
            {
                var uploadDir = ImageURLAvata;
                var geraralFileName = User.Identity.Name + DateTime.Now.ToString("yyyyMMddHHmmss") + "_chart";
                string NameFiletimeupload = geraralFileName;
                if (buyRecommendModel.ChartImange!=null)
                {
                    #region upload file                    
                    
                    var imagePath = Path.Combine(Server.MapPath(uploadDir), NameFiletimeupload + Path.GetExtension(buyRecommendModel.ChartImange.FileName));
                    buyRecommendModel.ChartImange.SaveAs(imagePath);
                    #endregion    
                }
                

                var recommentToDb = new RecommendStock();
                recommentToDb.CreatedDate = DateTime.Now.Date;
                recommentToDb.CreatedModify = DateTime.Now;
                recommentToDb.PostBy =  db.UserLogins.FirstOrDefault(u=> u.UserNameCopy == User.Identity.Name).Id;
                recommentToDb.StockCode = buyRecommendModel.StockCode;
                recommentToDb.StockHoldingTime = buyRecommendModel.StockHoldingTime;
                recommentToDb.TargetSell = buyRecommendModel.TargetSell;
                recommentToDb.BuyPrice = buyRecommendModel.BuyPrice;
                recommentToDb.Description = buyRecommendModel.Description;
                recommentToDb.TYPERecommend = "MUA";
                recommentToDb.SumComment = 0;
                if (buyRecommendModel.ChartImange != null)
                {
                    recommentToDb.ImageUrl = uploadDir + NameFiletimeupload + Path.GetExtension(buyRecommendModel.ChartImange.FileName);    
                }
                
                db.RecommendStocks.Add(recommentToDb);
                await db.SaveChangesAsync();
                return RedirectToAction("", "Home");
            }
            LoadInit();
            //ViewBag.PostBy = new SelectList(db.UserLogins, "Id", "KeyLogin", recommentToDb.PostBy);
            return View(buyRecommendModel);
        }
        private async Task LoadInit()
        {
            var listStock = (from s in dbstox.stox_tb_Company
                             where s.ExchangeID == 0 || s.ExchangeID == 1
                             orderby s.Ticker
                             select new
                             {
                                 Ticker = s.Ticker
                             }
                             ).ToList();
            ViewBag.listStockCode = new SelectList(listStock, "Ticker", "Ticker");

            var listTypeRecomendation = new List<dynamic>
                    { 
                        new { Id = "MUA", Name = "MUA" }
                        
                    }.ToList();

            ViewBag.listTypeRecomendation = new SelectList(listTypeRecomendation, "Id", "Name");

        }


        public async Task<ActionResult> Index()
        {

            var recommendstocks = db.RecommendStocks.Include(r => r.UserLogin);
            return View(await recommendstocks.ToListAsync());
        }

        // GET: /Recommendation/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RecommendStock recommendstock = await db.RecommendStocks.FindAsync(id);
            if (recommendstock == null)
            {
                return HttpNotFound();
            }
            return View(recommendstock);
        }

        // GET: /Recommendation/Create
        public ActionResult Create()
        {
            ViewBag.PostBy = new SelectList(db.UserLogins, "Id", "KeyLogin");
            return View();
        }

        // POST: /Recommendation/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include="ID,StockCode,TYPERecommend,BuyPrice,StockHoldingTime,TargetSell,Description,CreatedDate,PostBy")] RecommendStock recommendstock)
        {
            if (ModelState.IsValid)
            {
                recommendstock.CreatedDate = DateTime.Now.Date;
                db.RecommendStocks.Add(recommendstock);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.PostBy = new SelectList(db.UserLogins, "Id", "KeyLogin", recommendstock.PostBy);
            return View(recommendstock);
        }

        // GET: /Recommendation/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RecommendStock recommendstock = await db.RecommendStocks.FindAsync(id);
            if (recommendstock == null)
            {
                return HttpNotFound();
            }
            ViewBag.PostBy = new SelectList(db.UserLogins, "Id", "KeyLogin", recommendstock.PostBy);
            return View(recommendstock);
        }

        // POST: /Recommendation/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include="ID,StockCode,TYPERecommend,BuyPrice,StockHoldingTime,TargetSell,Description,CreatedDate,PostBy")] RecommendStock recommendstock)
        {
            if (ModelState.IsValid)
            {
                db.Entry(recommendstock).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.PostBy = new SelectList(db.UserLogins, "Id", "KeyLogin", recommendstock.PostBy);
            return View(recommendstock);
        }

        // GET: /Recommendation/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (User.Identity.Name != "long.thai")
            {
                return RedirectToAction("", "");
            }
            var commentrecommendstock = db.Comments.Where(cm => cm.PostedBy == id).ToList();
            RecommendStock recommendstock = await db.RecommendStocks.FindAsync(id);

            if (recommendstock == null)
            {
                return HttpNotFound();
            }
            db.Comments.RemoveRange(commentrecommendstock);
            db.RecommendStocks.Remove(recommendstock);
            await db.SaveChangesAsync();


            return RedirectToAction("ModifyRecommend" , "Home");
        }

        // POST: /Recommendation/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            RecommendStock recommendstock = await db.RecommendStocks.FindAsync(id);
            db.RecommendStocks.Remove(recommendstock);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        //--------------------------SELL

        public ActionResult SellRecommend()
        {
            //ViewBag.PostBy = new SelectList(db.UserLogins, "Id", "KeyLogin");
            LoadInitSell();
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> SellRecommend([Bind(Include = "ID,StockCode,BuyPrice,Description,ChartImange")] SellRecommendModel sellRecommendModel)
        {
            if (ModelState.IsValid)
            {
                var uploadDir = ImageURLAvata;
                var geraralFileName = User.Identity.Name + DateTime.Now.ToString("yyyyMMddHHmmss") + "_chart";
                string NameFiletimeupload = geraralFileName;
                if (sellRecommendModel.ChartImange != null)
                {
                    #region upload file

                    var imagePath = Path.Combine(Server.MapPath(uploadDir), NameFiletimeupload + Path.GetExtension(sellRecommendModel.ChartImange.FileName));
                    sellRecommendModel.ChartImange.SaveAs(imagePath);
                    #endregion
                }
                var recommentToDb = new RecommendStock();

                recommentToDb.CreatedDate = DateTime.Now.Date;

KhuyenNghiDauTu/PhimHang.vn/Views/Recommendation/BuyRecommend.cshtml
@model PhimHang.Models.BuyRecommendModel
@{
    ViewBag.Title = "Khuyến nghị mua";
    Layout = "~/Views/Shared/_Layout_Main.cshtml";
}

<h2>
    Khuyến nghị MUA
</h2>
@using (Html.BeginForm("BuyRecommend", "Recommendation", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()    
        <div id="example_length" class="dataTables_length1">
            <table class="form">
                <tr>
                    <td class="col1"><label> Mã cổ phiếu:</label></td>
                    <td class="col2">
                        @Html.DropDownList("StockCode", ViewBag.listStockCode as SelectList, string.Empty, new { id = "selectStockCode" })
                        @Html.ValidationMessageFor(model => model.StockCode)
                    </td>                    
                    
                    <td class="col1" style="margin-left:30px"><label> PE: </label><label id="lbPE" class="infoStox"></label></td>
                    <td></td>
                    <td class="col1" style="margin-left:30px"><label> KLCPLH: </label><label id="lbKLCPLH" class="infoStox"></label></td>
                    <td></td>
                    
                </tr>
                <tr>
                    <td class="col1"><label>Khuyến nghị:</label></td>
                    <td>
                        @Html.DropDownList("TYPERecommend", @ViewBag.listTypeRecomendation as SelectList, new { @name = "select", disabled = "disabled" })
                    </td>
                    <td class="col1" style="margin-left:30px"><label> PB: </label><label id="lbPB" class="infoStox"></label></td>
                    <td></td>
                    <td class="col1" style="margin-left:30px"><label> KLNY: </label><label id="lbKLNY" class="infoStox"></label></td>
                    <td></td>
                                    
                </tr>
                <tr>
                    <td class="col1"><label> Vùng giá mua:</label></td>
                    <td class="col2">
                        @Html.TextBoxFor(model => model.BuyPrice, new { id = "grumble" })
                        @Html.ValidationMessageFor(model => model.BuyPrice)
                    </td>
                   
                    <td class="col1" style="margin-left:30px"><label> EPS: </label><label id="lbEPS" class="infoStox"></label></td>
                    <td></td>
                    <td class="col1" style="margin-left:30px"><label> KLBQ 10 phiên: </label><label id="lbBQ10Phien" class="infoStox"></label></td>
                    <td></td>  
                </tr>
                <tr>
                    <td class="col1"><label>Thời gian nắm giữ (ngày):</label></td>
                    <td class="col2">
                        @Html.TextBoxFor(model => model.StockHoldingTime, new { id = "grumble", type = "number" })
                        @Html.ValidationMessageFor(model => model.StockHoldingTime)
                    </td>

                  
                </tr>

                <tr>
                    <td class="col1"><label>Giá bán mục tiêu:</label></td>
                    <td class="col2">
                        @*<input type="text" id="grumble" />*@
                        @Html.TextBoxFor(model => model.TargetSell, new { id = "grumble" })
                        @Html.ValidationMessageFor(model => model.TargetSell)
                    </td>

                    @*<td class="col1"><label> PE:</label><label>12.3</label></td>
                    <td></td>*@
                </tr>
                
                <tr>
                    <td class="col1" style="vertical-align: top;"><label>Chi tiết khuyến nghị:</label></td>
                    <td class="col2">@*<textarea cols="5" style="width:400px;height:80px" ></textarea>*@
                    @Html.TextAreaFor(model => model.Description, new { style = "width:400px;height:80px", cols = "5" })
                        @Html.ValidationMessageFor(model => model.Description)
                    
                    </td>
                                        
                </tr>
                <tr>
                    <td class="col1"><label>Hình chart:</label></td>
                    @*<td><input id="uploadchart" name="ChartImange" type="file"></td>*@
                    <td>
                        @Html.TextBoxFor(model => model.ChartImange, new { id = "grumble", type = "file" }) 
                        @Html.ValidationMessageFor(model => model.ChartImange)
                    </td>
                </tr>
            </table>
            <input type="submit" value="Lưu" class="btn btn-blue">
        </div>        
}

<script>
    $(function () {
        $('#selectStockCode').change(function () {
            $.ajax({
                cache: false,
                type: "GET",
                url: '@Url.Action("GetInfoStoxByAjax", "Recommendation")',
                data: { "selectStockCode": $('#selectStockCode').val() },
                beforeSend: function (xhr) {
                    //Add your image loader here
                    $('.infoStox').html('<img src="/images/ajax-loader.gif" />');
                    
                },
                success: function (data) {
                    $('.infoStox').html('');
                    $('#lbKLCPLH').html(data.KLCPLH);
                    $('#lbKLNY').html(data.KLNY);

                    $('#lbPE').html(data.PE);
                    $('#lbPB').html(data.PB);

                    $('#lbEPS').html(data.EPS);
                    $('#lbBQ10Phien').html(data.BQ10Phien);
                    
                },

            })
        });
    });
    $(window).load(function () {
        $('#selectStockCode').change();
    });
</script>

KhuyenNghiDauTu/PhimHang.vn/Views/Recommendation/Detail.cshtml
@model PhimHang.Models.RecommendStock
@{
    ViewBag.Title = "Chi tiết khuyến nghị";
    Layout = "~/Views/Shared/_Layout_Main.cshtml";
}
<script src="~/Scripts/jquery.timeago.js"></script>
<h2>
    Khuyến nghị @Model.TYPERecommend
</h2>

<div id="example_length" class="dataTables_length1">
    <table class="form">
        <tr>
            <td class="col1"><label> Người khuyến nghị:</label></td>
            <td class="col2">
                <input type="text" id="grumble" name="StockCode" value="@Model.UserLogin.UserNameCopy" disabled />                
                <label>Ngày:  @Model.CreatedModify.ToString("dd/MM/yyyy hh:mm:ss")</label>
            </td>
            <td class="col1" style="margin-left:30px"><label> PE: </label><label>@string.Format(System.Globalization.CultureInfo.GetCultureInfo("en-US"), "{0,0:N2}", @ViewBag.PE)</label></td>
            <td></td>
            <td class="col1" style="margin-left:30px"><label> KLCPLH: </label><label>@string.Format(System.Globalization.CultureInfo.GetCultureInfo("en-US"), "{0,0:N0}", @ViewBag.KLCPLH)</label></td>
            <td></td>
           
        </tr>
        <tr>
            <td class="col1"><label> Mã cổ phiếu:</label></td>
            <td class="col2">
                <input type="text" id="grumble" name="StockCode" value="@Model.StockCode" disabled />
            </td>
            <td class="col1" style="margin-left:30px"><label> PB: </label><label>@string.Format(System.Globalization.CultureInfo.GetCultureInfo("en-US"), "{0,0:N2}", @ViewBag.PB)</label></td>
            <td></td>
            <td class="col1" style="margin-left:30px"><label> KLNY: </label><label>@string.Format(System.Globalization.CultureInfo.GetCultureInfo("en-US"), "{0,0:N0}", @ViewBag.KLNY)</label></td>
            <td></td>
           
        </tr>
        <tr>
            <td class="col1"><label>Khuyến nghị:</label></td>
            <td>
                <input type="text" id="grumble" name="StockCode" value="@Model.TYPERecommend" disabled />
            </td>
            <td class="col1" style="margin-left:30px"><label> EPS: </label><label>@string.Format(System.Globalization.CultureInfo.GetCultureInfo("en-US"), "{0,0:N0}", @ViewBag.EPS)</label></td>
            <td></td>
            <td class="col1" style="margin-left:30px"><label> KLBQ 10 phiên: </label><label>@string.Format(System.Globalization.CultureInfo.GetCultureInfo("en-US"), "{0,0:N0}", @ViewBag.BQ10Phien)</label></td>
            <td></td>
        </tr>
        <tr>
            @{
                if (Model.TYPERecommend == "MUA")
                {
                    <td class="col1"><label> Vùng giá mua:</label></td>
                }
                else
                {
                    <td class="col1"><label> Vùng giá bán:</label></td>
                }
            }
            <td class="col2">
                <input type="text" id="grumble" name="StockCode" value="@Model.BuyPrice" disabled class="success" />
            </td>
            @{
                if (!string.IsNullOrWhiteSpace(Model.ImageUrl))
                {
                    <td>
                        <div class="chartImage">
                            <a href="@Model.ImageUrl" target="_blank"><img src="@Model.ImageUrl?width=450&height=280&mode=crop" /></a>
                        </div>
                    </td>
                }
            }
          
            
        </tr>
        @{
            if (Model.TYPERecommend == "MUA")
            {
                <tr>
                    <td class="col1"><label>Thời gian nắm giữ (ngày):</label></td>
                    <td class="col2">
                        <input type="text" id="grumble" name="StockCode" value="@Model.StockHoldingTime" disabled class="success" />
                    </td>

                   
                </tr>

                <tr>
                    <td class="col1"><label>Giá bán mục tiêu:</label></td>
                    <td class="col2">
                        <input type="text" id="grumble" name="StockCode" value="@Model.TargetSell" disabled class="success" />
                    </td>

                  
                </tr>
            }
        }
        <tr>
            <td class="col1" style="vertical-align: top;"><label>Chi tiết khuyến nghị:</label></td>
            <td class="col2">
                <textarea cols="5" disabled>@Model.Description</textarea>
            </td>
        </tr>
    </table>
    @*<input type="submit" value="Bình luận" class="btn btn-blue">*@
</div>
<br />
<br />
<!--Comment-->
<div id="CommentForKoLoad">
    <div class="bg-white">
        <div class="status-box">
            <div class="avatar-small">
                <img src="@ViewBag.AvataEmage?width=28&height=28&mode=crop" class="img-rounded" alt="avatar">
            </div>
            <div class="input-status">

                <div id="input-status-text" class="input-status-text">
                    <textarea data-bind="value : newMessage, valueUpdate : 'afterkeydown' , limitCharacters : 140" name="status" rows="5" placeholder="Nhập vào ít nhất 6 ký tự để bình luận" id="status" title="Search"></textarea>
                </div>
                <div class="status-control">
                    <div id="btnPhim" class="f-right">
                        <span data-bind="text : count"></span>
                        @*<a href="javascript:void(0)" class="button-phim" data-bind="click : addPost"><span>PHÍM</span></a>*@
                        <input id="bntSubmitComment" type="button" style="cursor:pointer; float:right" class="btn btn-blue" value="Bình luận" data-bind="click : addReply,  enable: enablePhimHang " />
                    </div>
                </div>
            </div>
        </div>
        <div class="list-status" data-bind="foreach : replys">
            <!--list comment here location.href='/Symbol/Details/' +-->
            <div class="list-item-status">
                <div class="avata-genaral-size">
                    <img class="img-rounded" alt="avatar" data-bind="attr: { src: ReplyByAvatar }">
                </div>
                <div class="list-item-detail">
                    <div class="list-item-date" data-bind="text : ReplyDate"></div>
                    <div class="list-item-username" data-bind="text : ReplyByName"></div>
                    <div style="cursor:pointer" class="list-item-status-content" data-bind="html : ReplyMessage "></div>
                    <div class="list-item-control">
                        @*<a class="button"><i class="fa fa-comments"></i>1</a>
                        <a style="cursor:pointer" class="button" data-bind="click : function() {  location.href='/PostDetail?postid='+ PostId +'&stock=' + StockPrimary }">Trả lời</a>
                        <a class="button">Chia sẻ</a>
                        <a class="button">Thích</a>*@
                        <a class="button">Báo cáo vi phạm</a>
                    </div>
                </div>
            </div>

            <!--end list comment-->

        </div>

       
    </div>
</div>
    <script type="text/javascript">
        function getTimeAgo(varDate) {
            if (varDate) {
                return $.timeago(varDate);
            }
            else {
                return '';
            }
        }
        function Post(data) {
            var self = this;
            data = data || {};
            self.ReplyId = data.ReplyId;
            self.ReplyMessage = ko.observable(data.ReplyMessage || "");
            self.ReplyByName = data.ReplyByName || "";
            self.ReplyByAvatar = data.ReplyByAvatar || "";
            self.ReplyDate = getTimeAgo(data.ReplyDate);

           


        }
        function viewModel() {
            var self = this;
            self.replys = ko.observableArray();
            self.newMessage = ko.observable('');
            self.error = ko.observable();

            // SignalR related
            //self.newPosts = ko.observableArray();
            // Reference the proxy for the hub.            

            self.init = function () {
                self.error(null);
                //self.hub.server.joinRoom('@ViewBag.StockCode');
                $.get('@Url.Action("GetCommentFromId", "Recommendation")',
                {
                    id: '@Model.ID'
                }, function (data) {
                    var mappedPosts = $.map(ko.utils.parseJson(data), function (item) { return new Post(item); });
                    $(mappedPosts).each(function (index, element) {
                        self.replys.push(element);
                    });
                })
            }


            self.addReply = function () { // khi click nut tra loi
                $('#bntSubmitComment').attr("disabled", true);
                self.error(null);               
                $.ajax({
                    cache: false,
                    type: "POST",
                    url: '@Url.Action("AddNewComment", "Recommendation")',
                    data: { "idkn": '@Model.ID', "messege": self.newMessage() },
                    beforeSend: function (xhr) {
                        //Add your image loader here
                        $('.infoStox').html('<img src="/images/ajax-loader.gif" />');
                    },
                    success: function (data) {
                        var mappedPosts = $.map(ko.utils.parseJson(data), function (item) { return new Post(item); });
                        $(mappedPosts).each(function (index, element) {
                            self.replys.unshift(element);
                        });
                        self.newMessage('');
                        //$('#bntSubmitComment').removeAttr("disabled");
                    },

                })

            }

            
            self.count = ko.computed(function () {
                var countNum = 140 - self.newMessage().length;
                return countNum;
            });


            self.enablePhimHang = ko.computed(function () {
                return self.newMessage().length <= 140 && self.newMessage().length >= 6;
            });


        }

        ko.bindingHandlers.limitCharacters = {
            update: function (element, valueAccessor, allBindingsAccessor, viewModel) {
                element.value = element.value.substr(0, valueAccessor());
                allBindingsAccessor().value(element.value.substr(0, valueAccessor()));
            }
        };
        
        var vmPost = new viewModel();
        ko.applyBindings(vmPost, document.getElementById("CommentForKoLoad"));
        vmPost.init();      
    </script>

KhuyenNghiDauTu/PhimHang.vn/Views/Recommendation/SellRecommend.cshtml
@model PhimHang.Models.SellRecommendModel
@{
    ViewBag.Title = "Khuyến nghị bán";
    Layout = "~/Views/Shared/_Layout_Main.cshtml";
}

<h2>
    Khuyến nghị BÁN
</h2>
@using (Html.BeginForm("SellRecommend", "Recommendation", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div id="example_length" class="dataTables_length1">
        <table class="form">
            <tr>
                <td class="col1"><label> Mã cổ phiếu:</label></td>
                <td class="col2">
                    @Html.DropDownList("StockCode", ViewBag.listStockCode as SelectList, string.Empty, new { id = "selectStockCode" })
                    @Html.ValidationMessageFor(model => model.StockCode)
                </td>
                <td class="col1" style="margin-left:30px"><label> PE: </label><label id="lbPE" class="infoStox"></label></td>
                <td></td>
                <td class="col1" style="margin-left:30px"><label> KLCPLH: </label><label id="lbKLCPLH" class="infoStox"></label></td>
                <td></td>

            </tr>
            <tr>
                <td class="col1"><label>Khuyến nghị:</label></td>
                <td>
                    @Html.DropDownList("TYPERecommend", @ViewBag.listTypeRecomendation as SelectList, new { @name = "select", disabled = "disabled" })
                </td>

                <td class="col1" style="margin-left:30px"><label> PB: </label><label id="lbPB" class="infoStox"></label></td>
                <td></td>
                <td class="col1" style="margin-left:30px"><label> KLNY: </label><label id="lbKLNY" class="infoStox"></label></td>
                <td></td>

            </tr>
            <tr>
                <td class="col1"><label> Vùng giá bán:</label></td>
                <td class="col2">
                    @Html.TextBoxFor(model => model.BuyPrice, new { id = "grumble" })
                    @Html.ValidationMessageFor(model => model.BuyPrice)
                </td>

                <td class="col1" style="margin-left:30px"><label> EPS: </label><label id="lbEPS" class="infoStox"></label></td>
                <td></td>
                <td class="col1" style="margin-left:30px"><label> KLBQ 10 phiên: </label><label id="lbBQ10Phien" class="infoStox"></label></td>
                <td></td>
                
            </tr>

            <tr>
                <td class="col1" style="vertical-align: top;"><label>Chi tiết khuyến nghị:</label></td>
                <td class="col2">
                    @*<textarea cols="5" style="width:400px;height:80px" ></textarea>*@
                    @Html.TextAreaFor(model => model.Description, new { style = "width:400px;height:80px", cols = "5" })
                    @Html.ValidationMessageFor(model => model.Description)

                </td>

            </tr>
            <tr>
                <td class="col1"><label>Hình chart:</label></td>
                @*<td><input id="uploadchart" name="ChartImange" type="file"></td>*@
                <td>
                    @Html.TextBoxFor(model => model.ChartImange, new { id = "grumble", type = "file" })
                    @Html.ValidationMessageFor(model => model.ChartImange)
                </td>
            </tr>
        </table>
   
    <input type="submit" value="Lưu" class="btn btn-blue">
</div>




}

<script>
    $(function () {
        $('#selectStockCode').change(function () {
            $.ajax({
                cache: false,
                type: "GET",
                url: '@Url.Action("GetInfoStoxByAjax", "Recommendation")',
                data: { "selectStockCode": $('#selectStockCode').val() },
                beforeSend: function (xhr) {
                    //Add your image loader here
                    $('.infoStox').html('<img src="/images/ajax-loader.gif" />');

                },
                success: function (data) {
                    $('.infoStox').html('<img src="/images/ajax-loader.gif" />');
                    $('#lbKLCPLH').html(data.KLCPLH);
                    $('#lbKLNY').html(data.KLNY);

                    $('#lbPE').html(data.PE);
                    $('#lbPB').html(data.PB);

                    $('#lbEPS').html(data.EPS);
                    $('#lbBQ10Phien').html(data.BQ10Phien);

                },

            })
        });
    });
    $(window).load(function () {
        $('#selectStockCode').change();
    });
</script>