tools.vfs.com.vn/PhimHang.vn/Controllers/ResearchController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PhimHang.Models;
using PagedList;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Web.Http.Results;

namespace PhimHang.Controllers
{
    [Authorize]
    public class ResearchController : Controller
    {
        //
        // GET: /Research/
        private VfsCustomerServiceEntities DbCustomerSV = new VfsCustomerServiceEntities();
        public async Task<ActionResult> Index( int[] CategoryIDs)
        {
            using (DbCustomerSV = new VfsCustomerServiceEntities())
            {                
                string tickerArray = Request.QueryString["ticker[]"];
                ViewBag.DescriptionTile = Resources.VN_Resources.Research_Title;
                ViewBag.Ticker = tickerArray;
                string tickerFilter = string.IsNullOrEmpty(tickerArray) ? "ALL" : tickerArray;
                DateTime dateVIPFilter = DateTime.Now;
                if (Request.Cookies["AccountType"] != null)
                {
                    dateVIPFilter = dateVIPFilter.AddDays(2);
                }
                LoadParameter(CategoryIDs);
                var listReport = new List<Report>();
                if (CategoryIDs == null)
                {
                    listReport = await (from r in DbCustomerSV.Reports.Include(r => r.ReportType)
                                        where (r.Ticker == tickerFilter || "ALL" == tickerFilter)
                                        && (r.DateViewCustomer <= dateVIPFilter)
                                        orderby r.CreateDate descending
                                        select r).Take(5).ToListAsync();
                }
                else
                {
                    listReport = await (from r in DbCustomerSV.Reports.Include(r => r.ReportType)
                                        where (r.Ticker == tickerFilter || "ALL" == tickerFilter)
                                        && (CategoryIDs.Contains(r.ReportType.Id))
                                        && (r.DateViewCustomer <= dateVIPFilter)
                                        orderby r.CreateDate descending
                                        select r).Take(5).ToListAsync();
                }

                return View(listReport);
            }

        }



        private void LoadParameter(int[] CategoryIDs)
        {
           
            var listTypeReport = new List<CheckBoxes>
                    { 
                        new CheckBoxes { Id = 1, Description = "Cảm nhận thị trường" },
                        new CheckBoxes { Id = 2, Description = "Phân tích cổ phiếu" },
                        new CheckBoxes{ Id = 3, Description = "Phân tích kỹ thuật" },
                        new CheckBoxes{ Id = 4, Description = "Báo cáo chiến lược" },
                        new CheckBoxes{ Id = 5, Description = "Phím hàng" },
                        new CheckBoxes{ Id = 6, Description = "Snapshot" }                        
                    }.ToList();
            if (CategoryIDs!=null)
            {
                foreach (var item in listTypeReport)
                {
                    if (CategoryIDs.Any(ct => ct == item.Id))
                    {
                        item.Checked = true;
                    }
                }
            }
            
            ViewBag.listTypeReport = listTypeReport; // load loai bao cao trong menu
        }

        public async Task<ActionResult> LoadMoreReport(int skipPostion, string ticker, int[] CategoryIDs)
        {
            //System.Threading.Thread.Sleep(6000);
            string tickerFilter = string.IsNullOrEmpty(ticker) ? "ALL" : ticker;
            DateTime dateVIPFilter = DateTime.Now; 
            if (Request.Cookies["AccountType"] != null)
            {
                dateVIPFilter = dateVIPFilter.AddDays(2); // neu la VIP dc xem tat ca cac report
            }
            using (DbCustomerSV = new VfsCustomerServiceEntities())
            {
                var listReport = new List<Report>();
                if (CategoryIDs == null)
                {
                    listReport = await (from r in DbCustomerSV.Reports.Include(r => r.ReportType)
                                        where (r.Ticker == tickerFilter || "ALL" == tickerFilter)
                                        && (r.DateViewCustomer <= dateVIPFilter)
                                        orderby r.CreateDate descending
                                        select r).Skip(skipPostion).Take(5).ToListAsync();

                }
                else
                {
                    listReport = await (from r in DbCustomerSV.Reports.Include(r => r.ReportType)
                                        where (r.Ticker == tickerFilter || "ALL" == tickerFilter)
                                        && (r.DateViewCustomer <= dateVIPFilter)
                                        && (CategoryIDs.Contains(r.ReportType.Id))
                                        orderby r.CreateDate descending
                                        select r).Skip(skipPostion).Take(5).ToListAsync();


                }
              
                return PartialView("_PartialListReport", listReport);
            }
        }
        private StoxDataEntities Stoxdb;
        public async Task<string> GetStockSuggest(string query)
        {
            if (!string.IsNullOrEmpty(query))
            {
                using (Stoxdb = new StoxDataEntities())
                {
                    var result = await (from tk in Stoxdb.stox_tb_Company
                                  where tk.Ticker.Contains(query)
                                  select new TickerSuggest
                                  {
                                      id = tk.Ticker,
                                      name = tk.ShortName
                                  }).ToListAsync();

                    return Newtonsoft.Json.JsonConvert.SerializeObject(result);
                    //return "[{name: 'Georges Washington',  email: 'georges.washington@whitehouse.gov'},{name: 'Theodore Roosevelt',email: 'theodore.roosevelt@whitehouse.gov'},{name: 'Benjamin Franklin',email: 'benjamin.franlin@whitehouse.gov'},{name: 'Abraham Lincoln',email: 'abraham.lincoln@whitehouse.gov'}]";
                }
            }
            else
            {
                return "[]";
            }

        }

	}
}

tools.vfs.com.vn/PhimHang.vn/Views/Research/Index.cshtml

@{
    ViewBag.Title = "Báo cáo phân tích";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    #menu-2 {
        /*background-color: rgb(245, 131, 31);*/
        background-color: #F29918;
    }
    #menu-2 a {
        color:#fff;
    }    
</style>
<link href="~/css/research.css" rel="stylesheet" />
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
<script src="~/Scripts/ExtentionJS.js"></script>
<!-- Latest compiled and minified JavaScript -->
<script src="http://nicolasbize.com/magicsuggest/tutorial/5/lib/magicsuggest/magicsuggest.js"></script>
<link href="~/css/magicsuggest.custom.css" rel="stylesheet" />
@*<script src="~/Js/magicsuggest-min.js"></script>*@
<script src="~/Js/ResearchJs.js"></script>
@*<link href="~/css/tableStyle.css" rel="stylesheet" />*@
<div id="div-table">
    <input type="hidden" name="hiddenTicker" value=@ViewBag.Ticker id="hiddenTicker" />
@using (Html.BeginForm("Index","Research",FormMethod.Get))
{
    <div class="box-filter">
        <section id="research-center">
            <div id="reseatch-category" class="list-wrapper">
                
                <div class="ms-parent">
                    <button type="button" class="ms-choice" style="width: 234px;" id="ms-dropReportType">
                        <span class="placeholder">Loại báo cáo phân tích</span>
                        <div class="" id="Arr-open"></div>
                    </button>
                    <div class="ms-drop bottom" style="width: 234px; text-align:left; display:none" id="ms-SelectReportType">
                        <ul style="max-height: 250px;">
                            @{
                            foreach (var item in ViewBag.listTypeReport as List<PhimHang.Models.CheckBoxes>)
                                {
                                    <li>
                                        <label>
                                            <input type="checkbox" name="CategoryIDs" value=@item.Id onclick="this.form.submit();"
                                              @{
                                                if (item.Checked == true)
                                                {
                                                    <text> checked="checked"</text>
                                                }
                                              }     
                                                   
                                               >@item.Description
                                        </label>
                                    </li>
                                }
                            }                            
                        </ul>
                    </div>
                </div>
            </div>

            <div class="search-box">
                <!--<input class="form-control" id="auto-suggest" type="search" name="research_search" placeholder=" / company name / key word" />-->
                
                <div class="ms-ctn form-control  ms-ctn-focus">
                    <span class="ms-helper " style="display: none;"></span>
                    <div class="ms-sel-ctn">
                        <input type="text"  title="tìm báo cáo" style="width: 412px; color: #0065BF; overflow-x:hidden " maxlength="10" name="ticker[]" id="auto-suggest">
                        <div style="display: none;"></div>
                    </div>
                    @*<div class="ms-trigger">
                        <div class="ms-trigger-ico"></div>
                    </div>*@
                </div>
                <button id="btn-submit" type="submit" style="cursor:pointer">
                    <i style="margin-left:-8px" class="fa fa-search"></i>
                </button>
            </div>

            <ul class="ctn-view-list">
                <!--load danh sách report ở đây ?-->
               @Html.Partial("_PartialListReport")
                             
            </ul>
            <ul>

                <li>
                    <span class="readMore">
                        <a href="javascript:void(0)"  id="readMore">Xem thêm</a>
                    </span>
                    <span id="loading-image" style="display:none"><img src="/images/uploading.gif" /></span>
                </li>
            </ul>
        </section>
    </div>
}
</div> <!--end div-table -->

@{
    if (string.IsNullOrEmpty(@ViewBag.Ticker))
    {
        <script>
            $(document).ready(function () {
                $('#auto-suggest').magicSuggest({
                    data: '/Research/GetStockSuggest',
                    placeholder: 'Nhập mã cổ phiếu: HAG, VNM, KBC, ...',
                    method: 'get',
                    maxSelection: 1,
                    name: 'ticker[]',
                    allowFreeEntries: false,
                    valueField: 'id',
                    displayField: 'id',
                    renderer: function (data) {
                        return data.id + ' (<b>' + data.name + '</b>)';
                    },
                   
                });
            });
        </script>
    }
    else
    {
        <script>
            $(document).ready(function () {
                $('#auto-suggest').magicSuggest({
                    data: '/Research/GetStockSuggest',
                    placeholder: 'Nhập mã cổ phiếu: HAG, VNM, KBC, ...',
                    method: 'get',
                    maxSelection: 1,
                    name: 'ticker[]',
                    allowFreeEntries: false,
                    valueField: 'id',
                    displayField: 'id',
                    renderer: function (data) {
                        return data.id + ' (<b>' + data.name + '</b>)';
                    },
                    value: [{
                        'id': '@ViewBag.Ticker',
                        'name': '@ViewBag.Ticker'
                    }],


                });
            });
        </script>
    }
}

tools.vfs.com.vn/PhimHang.vn/Views/Research/_PartialListReport.cshtml
@model List<PhimHang.Models.Report>
@{
    foreach (var item in Model)
    {
        <li class="item-research">
            <time>@item.CreateDate.ToString("dd/MM/yyyy HH:MM:ss")</time>
            <div>
                <a href="/upload/@item.UploadDir" target="_blank">
                    <h2>@item.Title</h2>
                </a>

                <ul class="research-type">
                    <li class="main-report"><i class="fa fa-folder"></i>@item.ReportType.Description</li>

                </ul>
                <div class="tags">

                </div>
                <a href="/upload/@item.UploadDir" target="_blank">
                    <small class="btn-dl">
                        
                        @item.FileSize KB | <i class="fa fa-eye"></i> @item.TotalDownload 
                    </small>
                    
                </a>
                
            </div>
        </li>
    }
}

<script>
    $(document).ready(function () {
        if ('@Model.Count' == 5) {
            $('.readMore').fadeIn();
        }
        else {
            $('.readMore').fadeOut();
        }
        
    });
</script>